# -*- coding: utf-8 -*-
"""qr-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aU6hhjY9bUhzxoEXHbsu6hqS0QGkNrz0
"""

pip install qrcode



import qrcode

# Replace 'member_id_value' with the actual member ID
member_id = eval(input("member ID: "))

# Create the QR code
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=4,
)
qr.add_data(member_id)
qr.make(fit=True)

# Save the QR code to a file
img = qr.make_image(fill_color="black", back_color="white")
format = ".png"
img.save(str(member_id) + format)